import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Sidebar from "examenfinal/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Sidebar />
        {children}
        </body>
    </html>
  );
}
